env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - prettier:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'semi': ['error', 'always'],
    'quotes': ['error', 'single'],
    'prettier/prettier': ['error'],
  }
settings:
  react:
    version: 'detect'
